[theme]
base="light"
primaryColor="#2979bf"

# Operation Trust Me Bro (https://www.schemecolor.com/trustworthy-business.php)
# primaryColor="#2979bf"
# primaryColor="#233b86"
# primaryColor="#b2b2b2"
# primaryColor="#ffddb5"

# Old Color
# primaryColor="#0054A5"
